// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"tiny_service/apps/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/app/user/add",
				Handler: UserRegHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/app/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/app/product/add",
				Handler: AddProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/app/product/del",
				Handler: DelProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/app/product/get",
				Handler: GetProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/app/product/list",
				Handler: GetProductListHandler(serverCtx),
			},
		},
	)
}
