// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: user.proto

package server

import (
	"context"

	"tiny_service/apps/user/user/internal/logic"
	"tiny_service/apps/user/user/internal/svc"
	"tiny_service/apps/user/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Reg(ctx context.Context, in *user.UserRegRequest) (*user.UserRegResponse, error) {
	l := logic.NewRegLogic(ctx, s.svcCtx)
	return l.Reg(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.UserLoginRequest) (*user.UserLoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
