// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type UserLoginrequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginresponse struct {
	Id    int64  `json:"id"`
	Token string `json:"token"`
}

type UserRegrequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserRegresponse struct {
	Id int64 `json:"id"`
}
